import test from "node:test";import assert from"node:assert/strict";import{loginSchema,}from"../src/modules/auth/auth.schemas.js";import{groupSchema,projectSchema}from"../src/modules/common/schemas.js";import{hashToken}from"../src/lib/auth/token.js";import{requirePermission}from"../src/lib/permissions/check.js";import{AuthorizationError}from"../src/lib/errors/index.js";import{runTransaction}from"../src/lib/db/transaction.js";
test("login validation normalizes email and rejects a short password",()=>{assert.equal(loginSchema.parse({email:" ADMIN@EXAMPLE.ORG ",password:"long-password"}).email,"admin@example.org");assert.equal(loginSchema.safeParse({email:"bad",password:"x"}).success,false)});
test("project and group validation enforce constrained statuses and UUIDs",()=>{assert.equal(projectSchema.safeParse({code:'X1',name:'Pilot',status:'BROKEN'}).success,false);assert.equal(groupSchema.safeParse({name:'Unity',projectId:'no',stateId:'no'}).success,false)});
test("session token hashing is deterministic and non-plaintext",()=>{assert.equal(hashToken('secret'),hashToken('secret'));assert.notEqual(hashToken('secret'),'secret')});
test("permission resolution denies missing permission",()=>{assert.throws(()=>requirePermission({permissions:['group.view']},'group.create'),AuthorizationError)});
test("transaction rolls back and releases on failure",async()=>{const calls=[],client={query:async sql=>{calls.push(sql);if(sql==='WORK')throw new Error('boom')},release:()=>calls.push('RELEASE')},fakePool={connect:async()=>client};await assert.rejects(()=>runTransaction(fakePool,c=>c.query('WORK')));assert.deepEqual(calls,['BEGIN','WORK','ROLLBACK','RELEASE'])});
test("transaction commits and releases on success",async()=>{const calls=[],client={query:async sql=>calls.push(sql),release:()=>calls.push('RELEASE')};await runTransaction({connect:async()=>client},c=>c.query('WORK'));assert.deepEqual(calls,['BEGIN','WORK','COMMIT','RELEASE'])});
test("facilitator A is denied access when scoped group query returns no row",async()=>{const {checkGroupAccess}=await import("../src/lib/permissions/group-scope.js");const facilitator={id:'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',organization_id:'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',roles:['FACILITATOR']};await assert.rejects(()=>checkGroupAccess(async()=>[],facilitator,'cccccccc-cccc-4ccc-8ccc-cccccccccccc'),AuthorizationError)});
test("group scope SQL grants broad scope only to project admins and state coordinators",async()=>{const {checkGroupAccess}=await import("../src/lib/permissions/group-scope.js");let sql='';await checkGroupAccess(async text=>{sql=text;return[{id:'group'}]},{id:'user',organization_id:'org',roles:['FACILITATOR']},'group');assert.match(sql,/r\.code IN \('PROJECT_ADMIN','STATE_COORDINATOR'\)/);assert.doesNotMatch(sql,/r\.code IN \([^)]*FACILITATOR/)});
