import {z} from "zod";
export const listSchema=z.object({page:z.coerce.number().int().min(1).default(1),pageSize:z.coerce.number().int().min(1).max(100).default(20),search:z.string().trim().max(100).default(""),status:z.string().optional(),projectId:z.string().uuid().optional(),stateId:z.string().uuid().optional(),lgaId:z.string().uuid().optional(),facilitatorId:z.string().uuid().optional()});
export const projectSchema=z.object({code:z.string().trim().min(2).max(40).transform(v=>v.toUpperCase()),name:z.string().trim().min(2).max(180),description:z.string().max(2000).nullable().optional(),startDate:z.string().date().nullable().optional(),endDate:z.string().date().nullable().optional(),status:z.enum(['DRAFT','ACTIVE','COMPLETED','SUSPENDED','ARCHIVED']).default('DRAFT')});
export const userSchema=z.object({firstName:z.string().trim().min(1).max(100),lastName:z.string().trim().min(1).max(100),email:z.string().trim().toLowerCase().email(),phone:z.string().trim().max(30).optional(),password:z.string().min(12).max(128),status:z.enum(['ACTIVE','INACTIVE','SUSPENDED','LOCKED']).default('ACTIVE'),roleCode:z.enum(['SUPER_ADMIN','PROJECT_ADMIN','STATE_COORDINATOR','FACILITATOR','VSLA_MEMBER']),projectId:z.string().uuid().nullable().optional(),stateId:z.string().uuid().nullable().optional()});
export const userUpdateSchema=z.object({firstName:z.string().trim().min(1).max(100).optional(),lastName:z.string().trim().min(1).max(100).optional(),phone:z.string().trim().max(30).nullable().optional(),status:z.enum(['ACTIVE','INACTIVE','SUSPENDED','LOCKED']).optional()}).strict().refine(value=>Object.keys(value).length>0,"At least one user field is required");
const optionalUuid=z.preprocess(v=>v===''?null:v,z.string().uuid().nullable().optional());
const optionalText=(max)=>z.preprocess(v=>typeof v==='string'&&v.trim()===''?null:v,z.string().trim().max(max).nullable().optional());
export const groupSchema=z.object({name:z.string().trim().min(2).max(180),projectId:z.string().uuid(),stateId:z.string().uuid(),lgaId:z.string().uuid(),communityId:optionalUuid,communityName:optionalText(300),facilitatorUserId:optionalUuid,dateFormed:z.preprocess(v=>v===''?null:v,z.string().date().nullable().optional()),meetingLocation:optionalText(500),expectedMemberCount:z.preprocess(v=>v===''?null:v,z.coerce.number().int().min(15).max(30).nullable().optional()),notes:optionalText(2000),groupType:z.enum(['SUPERVISED','SELF_MANAGED']).default('SUPERVISED'),status:z.enum(['DRAFT','ONBOARDING','ACTIVE','SUSPENDED','CLOSED','ARCHIVED']).default('ONBOARDING')});
export const archiveGroupSchema=z.object({reason:z.string().trim().min(5).max(2000),confirmation:z.literal('ARCHIVE')}).strict();
