import Link from "next/link";
import { notFound } from "next/navigation";
import { requireAuth } from "@/lib/auth/session";
import { requireGroupRouteAction, canGroupAction, GROUP_ACTION } from "@/modules/group-access/group-access.service";
import { query } from "@/lib/db/query";
import GroupNav from "@/components/group-nav";
import OperatingModelPanel from "@/components/operating-model-panel";
import PublicDiscoveryPanel from "@/components/public-discovery-panel";
import ArchiveGroupAction from "@/components/archive-group-action";
import { formatDate } from "@/lib/utils/date";
import { formatCurrency } from "@/lib/utils/money";

export default async function GroupDetail({ params }) {
  const { id } = await params, user = await requireAuth(), actor = await requireGroupRouteAction(user, id, "group.view", GROUP_ACTION.GROUP_VIEW);
  const [group] = await query(`SELECT g.*,p.name project_name,s.name state_name,l.name lga_name,concat(u.first_name,' ',u.last_name) facilitator_name,(SELECT COUNT(*)::int FROM group_members m WHERE m.group_id=g.id AND m.status='ACTIVE') member_count,(SELECT cycle_number FROM vsla_cycles c WHERE c.group_id=g.id AND c.status='ACTIVE' LIMIT 1) current_cycle,(SELECT version_number FROM group_constitutions c WHERE c.group_id=g.id AND c.status='APPROVED' LIMIT 1) constitution_version,(SELECT meeting_frequency FROM group_constitutions c WHERE c.group_id=g.id AND c.status='APPROVED' LIMIT 1) meeting_frequency FROM vsla_groups g JOIN projects p ON p.id=g.project_id LEFT JOIN states s ON s.id=g.state_id LEFT JOIN lgas l ON l.id=g.lga_id LEFT JOIN users u ON u.id=g.facilitator_user_id WHERE g.id=$1 AND g.organization_id=$2`, [id,user.organization_id]);
  if (!group) notFound();
  const [community] = await query(`SELECT COALESCE(NULLIF(TRIM(g.community_name), ''), c.name) AS community_display_name FROM vsla_groups g LEFT JOIN communities c ON c.id=g.community_id WHERE g.id=$1`,[id]);
  const [financial] = await query(`WITH active_cycle AS (SELECT id FROM vsla_cycles WHERE group_id=$1 AND status='ACTIVE' LIMIT 1), balances AS (SELECT la.account_code,COALESCE(SUM(CASE le.entry_side WHEN 'DEBIT' THEN le.amount ELSE -le.amount END),0)::numeric(18,2) balance FROM active_cycle ac JOIN ledger_accounts la ON la.cycle_id=ac.id LEFT JOIN ledger_entries le ON le.ledger_account_id=la.id GROUP BY la.account_code), latest_reconciliation AS (SELECT mr.savings_loan_difference,mr.social_fund_difference FROM meeting_reconciliations mr JOIN vsla_meetings vm ON vm.id=mr.meeting_id JOIN active_cycle ac ON ac.id=vm.cycle_id ORDER BY mr.created_at DESC LIMIT 1) SELECT (SELECT id FROM active_cycle) cycle_id,COALESCE((SELECT balance FROM balances WHERE account_code='MEMBER_SAVINGS_CONTROL'),0)::numeric(18,2) member_savings,COALESCE((SELECT balance FROM balances WHERE account_code='SAVINGS_LOAN_CASH'),0)::numeric(18,2) available_loan_fund,COALESCE((SELECT balance FROM balances WHERE account_code='SOCIAL_FUND_CASH'),0)::numeric(18,2) social_fund,COALESCE((SELECT balance FROM balances WHERE account_code='LOANS_RECEIVABLE'),0)::numeric(18,2) outstanding_loans,COALESCE((SELECT balance FROM balances WHERE account_code='LOAN_SERVICE_CHARGE_INCOME'),0)::numeric(18,2) service_charge_earned,COALESCE((SELECT ABS(savings_loan_difference)+ABS(social_fund_difference) FROM latest_reconciliation),0)::numeric(18,2) reconciliation_variance`, [id]);
  const canViewReadiness = actor.has_program_scope && user.permissions.includes("group_operation_mode.view"), canManageMode = actor.has_program_scope && user.permissions.includes("group_operation_mode.manage"), canManageAccess = user.permissions.includes("member_access.manage") && canGroupAction(user,actor,GROUP_ACTION.DIGITAL_ACCESS_MANAGE), canManagePublic = user.permissions.includes("group_public.manage") && canGroupAction(user,actor,GROUP_ACTION.GROUP_MANAGE);
  const leaders = await query(`SELECT oa.position_code,m.id member_id,concat(m.first_name,' ',m.last_name) member_name,(m.linked_user_id IS NOT NULL AND u.status='ACTIVE') login_enabled FROM group_officer_assignments oa JOIN vsla_cycles cy ON cy.id=oa.cycle_id AND cy.status='ACTIVE' JOIN group_members m ON m.id=oa.member_id LEFT JOIN users u ON u.id=m.linked_user_id WHERE oa.group_id=$1 AND oa.status='ACTIVE' AND oa.position_code IN('CHAIRPERSON','RECORD_KEEPER') ORDER BY CASE oa.position_code WHEN 'CHAIRPERSON' THEN 1 ELSE 2 END`,[id]);
  const summaries = [["Project",group.project_name],["Location",[community?.community_display_name,group.lga_name,group.state_name].filter(Boolean).join(", ")],["Agent",group.facilitator_name],["Date Formed",formatDate(group.date_formed)],["Current Cycle",group.current_cycle||"Not active"],["Active Members",group.member_count],["Constitution",group.constitution_version?`Version ${group.constitution_version}`:"Not approved"],["Meeting",group.meeting_frequency||"Not configured"]];
  const finances = [["Member Savings",String(financial.member_savings).replace(/^-/,'')],["Available Loan Fund",financial.available_loan_fund],["Social Fund",financial.social_fund],["Outstanding Loans",financial.outstanding_loans],["Service Charge Earned",String(financial.service_charge_earned).replace(/^-/,'')],["Reconciliation Variance",financial.reconciliation_variance]];
  return <><div className="group-overview-heading"><div><h1>{group.name}</h1><p className="muted">{group.group_code} · {group.status}</p></div><div className="group-heading-actions">{["DRAFT","ONBOARDING"].includes(group.status)&&<Link className="button" href={`/groups/${id}/onboarding`}>Continue onboarding</Link>}{group.status!=="ARCHIVED"&&actor.has_program_scope&&user.permissions.includes("group.archive")&&<ArchiveGroupAction groupId={id} groupName={group.name}/>}</div></div><GroupNav id={id}/><section className="current-cycle-finance"><p className="eyebrow">Current Cycle Finance</p><h2>{group.current_cycle?`Cycle ${group.current_cycle}`:"No active cycle"}</h2>{financial.cycle_id?<div className="finance-card-grid">{finances.map(([label,value])=><article className="panel" key={label}><span>{label}</span><strong>{formatCurrency(value)}</strong></article>)}</div>:<p className="muted">Activate a cycle to view current-cycle financial information.</p>}</section><div className="grid cards">{summaries.map(([label,value])=><article key={label} className="panel" style={{padding:20}}><span className="muted">{label}</span><h3>{value||"—"}</h3></article>)}</div><OperatingModelPanel groupId={id} operationMode={group.operation_mode} facilitatorName={group.facilitator_name} canViewReadiness={canViewReadiness} canManageMode={canManageMode}/><section className="panel leadership-access-panel"><p className="eyebrow">Leadership access</p><h2>Member leadership</h2><div className="leadership-access-grid">{leaders.map(leader=><div key={leader.position_code}><span>{leader.position_code==="CHAIRPERSON"?"Chairperson":"Secretary / Record-Keeper"}</span><strong>{leader.member_name}</strong><small className={leader.login_enabled?"login-enabled":"muted"}>Login: {leader.login_enabled?"Enabled ✓":"Not enabled"}</small>{canManageAccess&&<Link href={`/groups/${id}/members/${leader.member_id}`}>Manage Access</Link>}</div>)}{!leaders.length&&<p className="muted">Leadership assignments are not yet complete.</p>}</div></section><PublicDiscoveryPanel groupId={id} groupStatus={group.status} publicVisibility={group.public_visibility} membershipIntakeStatus={group.membership_intake_status} canManage={canManagePublic}/></>;
}
