import Image from "next/image";
import Link from "next/link";
import PublicNav from "@/components/public-nav";

const features=[
  ["01","Member management","Keep group membership, leadership and digital access organized in one secure place."],
  ["02","Meeting records","Capture attendance, contributions and decisions around each real group meeting."],
  ["03","Savings and loans","Support transparent savings, responsible lending and clear member histories."],
  ["04","Social Fund","Keep community support funds distinct, accountable and easy to reconcile."],
];

export default function Home(){return <main className="public-site">
  <section className="landing-hero"><PublicNav/><div className="landing-hero-grid">
    <div className="landing-copy"><p className="landing-kicker"><span/>Community finance, made clearer</p><h1>A smarter way to manage community savings groups</h1><p className="landing-lede">Visave helps communities manage members, meetings, savings, loans and Social Fund activities with greater transparency and accountability.</p><div className="landing-actions"><Link className="landing-primary" href="/find-a-group">Find a Group</Link><Link className="landing-secondary" href="#solutions">Explore the Platform <span aria-hidden="true">→</span></Link></div><p className="landing-trust">Built for member leadership. Supported by trained Agents.</p></div>
    <div className="hero-visual"><div className="hero-accent" aria-hidden="true"/><div className="hero-image-clip"><Image src="/images/vsla-community-hero.png" alt="Illustrative community savings group reviewing records together" fill priority sizes="(max-width: 900px) 92vw, 52vw"/></div><div className="product-preview"><div className="preview-copy"><Image className="preview-logo" src="/cccrn-logo.png" alt="CCCRN logo" width={190} height={148}/><div><strong>Visave</strong><small>Clear records. Stronger groups.</small></div></div><div className="phone-stack" aria-label="Illustrative platform interface preview"><div className="phone phone-back"><span className="phone-speaker"/><div className="phone-screen"><small>GROUP OVERVIEW</small><b>Unity Savings Group</b><i/><i/><i/></div></div><div className="phone phone-front"><span className="phone-speaker"/><div className="phone-screen"><small>THIS MEETING</small><b>₦42,000</b><div className="mini-chart"><span/><span/><span/><span/></div><em>Reconciled ✓</em></div></div></div></div></div>
  </div></section>
  <section className="landing-section platform-support" id="solutions"><div className="section-heading"><p className="section-kicker">One connected platform</p><h2>Everything a savings group needs to operate with confidence.</h2><p>Purpose-built workflows connect programme teams, Agents and elected group leaders without replacing the way communities make decisions.</p></div><div className="feature-grid">{features.map(([number,title,copy])=><article key={number}><span>{number}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></section>
  <section className="landing-section workflow-section"><div className="workflow-copy"><p className="section-kicker">How it works</p><h2>Support that leads to member management.</h2><p>CCCRN programme teams establish accountable structures. Agents prepare and train groups. Elected leaders take operational ownership when the group is ready.</p><Link href="/about">Learn about the programme <span aria-hidden="true">→</span></Link></div><ol className="workflow-steps"><li><span>01</span><div><b>Programme team</b><small>Governance and oversight</small></div></li><li><span>02</span><div><b>Trained Agent</b><small>Formation, setup and support</small></div></li><li><span>03</span><div><b>Savings group</b><small>Constitution and shared decisions</small></div></li><li><span>04</span><div><b>Member leadership</b><small>Transparent day-to-day operation</small></div></li></ol></section>
  <section className="landing-section value-section"><div className="value-panel"><p className="section-kicker">Designed for accountability</p><h2>Better records create stronger community institutions.</h2><div className="value-list"><span>Greater transparency</span><span>Easier supervision</span><span>Reliable financial histories</span><span>Member-managed operations</span></div></div><aside><p>Looking for a savings group near you?</p><h2>Discover groups that are open to new members.</h2><Link className="landing-primary" href="/find-a-group">Find a Group</Link></aside></section>
  <section className="final-cta"><p className="section-kicker">Start here</p><h2>Community savings, supported by better digital tools.</h2><div className="landing-actions"><Link className="landing-primary" href="/find-a-group">Find a Group</Link><Link className="landing-secondary light" href="/login">Platform Login <span aria-hidden="true">→</span></Link></div></section>
  <footer className="public-footer"><div className="public-brand"><Image className="public-brand-logo" src="/cccrn-logo.png" alt="CCCRN logo" width={190} height={148}/><span><strong>Visave</strong></span></div><p>Supporting transparent, member-led savings groups.</p><div><Link href="/about">About</Link><Link href="/join-a-group">Join a Group</Link><Link href="/contact">Contact</Link><Link href="/login">Login</Link></div></footer>
</main>}
