"use client";
import Link from "next/link";
import {useState} from "react";
import {useRouter} from "next/navigation";
import {formatCurrency} from "@/lib/utils/money";
import FinalReconciliationRefresh from "@/components/final-reconciliation-refresh";

const labels={GROUP_NOT_ACTIVE:"The group is not active.",CYCLE_NOT_ACTIVE:"The cycle is not active.",NO_FINAL_OPEN_MEETING:"Open the final meeting before preparing share-out.",OPEN_PRIOR_MEETINGS:"Resolve all earlier meetings first.",FINAL_MEETING_NOT_LATEST:"The selected final meeting is not the latest valid meeting.",OUTSTANDING_LOANS:"Settle all outstanding loan principal and service charge.",UNRESOLVED_LOAN_REQUESTS:"Resolve all pending or approved loan requests.",LOAN_RECEIVABLE_DISCREPANCY:"Loans Receivable does not reconcile to zero.",SAVINGS_CONTROL_DISCREPANCY:"Member savings do not reconcile with the control account.",DISTRIBUTABLE_FUND_DISCREPANCY:"The distributable fund does not reconcile.",NO_MEMBER_SHARES:"At least one net share is required.",UNBALANCED_LEDGER:"An unbalanced financial transaction exists.",SAVINGS_SHARE_VALUE_DISCREPANCY:"A savings row does not match shares multiplied by its recorded share value.",CYCLE_NOT_CLOSING:"The cycle has not entered closing.",SHAREOUT_NOT_COMPLETED:"Complete all member payouts first.",FINAL_MEETING_NOT_CLOSED:"Close the final meeting.",FINAL_RECONCILIATION_NOT_BALANCED:"The final reconciliation must be balanced.",FINAL_RECONCILIATION_STALE:"The final reconciliation no longer matches current balances.",SOCIAL_FUND_NOT_CARRIED_FORWARD:"Carry the Social Fund into the next cycle."};
const money=value=>formatCurrency(value??"0.00");

export default function ShareoutPanel({groupId,cycleId,initialReadiness,initialDetail,transition,finalReconciliation,capabilities}){
  const[message,setMessage]=useState("");const[busy,setBusy]=useState(false);const router=useRouter();
  const shareout=initialDetail?.shareout,items=initialDetail?.entitlements||[],state=initialReadiness.state||{},closure=transition.closure,next=transition.nextCycle,meetingId=shareout?.final_meeting_id||state.meeting_id;
  const total=items.reduce((sum,item)=>sum+Number(item.final_entitlement),0),difference=Number(shareout?.distributable_fund||0)-total;
  async function post(path,body={}){setBusy(true);setMessage("");try{const response=await fetch(path,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)}),result=await response.json();if(!response.ok){setMessage(result.error?.message||"Action failed");return}router.refresh()}catch{setMessage("The action could not be completed. Try again.")}finally{setBusy(false)}}
  const explain=code=>labels[code]||code.replaceAll("_"," ").toLowerCase();
  return <div className="grid" style={{gap:18}}>
    {message&&<p className="panel" role="alert" style={{padding:12,color:"#a22"}}>{message}</p>}
    <section className="panel" style={{padding:20}}><h2>Share-out readiness</h2><p><span className="badge">{initialReadiness.ready?"READY":"BLOCKED"}</span></p>
      <div className="grid grid-3"><p><strong>Total net savings</strong><br/>{money(state.total_savings)}</p><p><strong>Collected fines</strong><br/>{money(state.fine_income)}</p><p><strong>Collected service charge</strong><br/>{money(state.charge_income)}</p><p><strong>Distributable pool</strong><br/>{money(state.savings_cash)}</p><p><strong>Total net shares</strong><br/>{state.total_shares??0}</p><p><strong>Included members</strong><br/>{state.included_members??0}</p><p><strong>Social Fund balance</strong><br/>{money(state.social_cash)}</p><p><strong>Outstanding loans</strong><br/>{state.outstanding_loans??0}</p><p><strong>Unresolved requests</strong><br/>{state.unresolved_requests??0}</p></div>
      {initialReadiness.blockingIssues.map(code=><p key={code}>• {explain(code)}</p>)}
      {capabilities.prepare&&!shareout&&initialReadiness.ready&&meetingId&&<button disabled={busy} onClick={()=>post(`/api/v1/groups/${groupId}/meetings/${meetingId}/shareout/prepare`)}>Prepare share-out</button>}
    </section>
    {shareout&&<section className="panel" style={{padding:20}}><h2>Share-out v{shareout.version_number} <span className="badge">{shareout.status}</span></h2><p>Share-out distributes the Savings/Loan Fund in proportion to each member&apos;s net shares.</p>
      <div className="grid grid-3"><p><strong>Distributable pool</strong><br/>{money(shareout.distributable_fund)}</p><p><strong>Total entitlements</strong><br/>{money(total)}</p><p><strong>Difference</strong><br/>{money(difference)}</p></div>
      {capabilities.approve&&shareout.status==="DRAFT"&&<button disabled={busy} onClick={()=>window.confirm("Approve this share-out? The cycle will enter CLOSING, ordinary financial activity will freeze, and this entitlement snapshot will become authoritative.")&&post(`/api/v1/groups/${groupId}/cycles/${cycleId}/shareout/${shareout.id}/approve`,{idempotencyKey:crypto.randomUUID()})}>Review and approve</button>}
      <div className="table-wrap"><table><thead><tr><th>Member</th><th>Status</th><th>Shares</th><th>Savings</th><th>Ratio</th><th>Surplus</th><th>Entitlement</th><th>Paid / remaining</th><th>Action</th></tr></thead><tbody>{items.map(item=>{const history=item.payout_history||[],reversed=new Set(history.filter(x=>x.kind==="REVERSAL").map(x=>x.originalPayoutId)),active=history.find(x=>x.kind==="PAYOUT"&&!reversed.has(x.id)),remaining=Number(item.final_entitlement)-Number(item.net_paid),ratio=Number(shareout.total_net_shares)?Number(item.net_shares)/Number(shareout.total_net_shares)*100:0;return <tr key={item.id}><td>{item.member_code_snapshot} · {item.member_name_snapshot}</td><td><span className="badge">{item.member_status}</span></td><td>{item.net_shares}</td><td>{money(item.net_savings)}</td><td>{ratio.toFixed(2)}%</td><td>{money(item.surplus_amount)}</td><td>{money(item.final_entitlement)}</td><td>{money(item.net_paid)} / {money(remaining)}</td><td>{capabilities.payout&&meetingId&&["APPROVED","PAYOUT_IN_PROGRESS"].includes(shareout.status)&&remaining===Number(item.final_entitlement)&&Number(item.final_entitlement)>0&&<button disabled={busy} onClick={()=>post(`/api/v1/groups/${groupId}/meetings/${meetingId}/shareout/${shareout.id}/payouts`,{entitlementId:item.id,idempotencyKey:crypto.randomUUID()})}>Record payout</button>}{capabilities.payout&&active&&shareout.status!=="COMPLETED"&&<button className="secondary" disabled={busy} onClick={()=>post(`/api/v1/groups/${groupId}/meetings/${meetingId}/shareout/${shareout.id}/payouts/${active.id}/reverse`,{idempotencyKey:crypto.randomUUID()})}>Reverse payout</button>}{history.length>0&&<details><summary>History</summary>{history.map(x=><p key={x.id}>{x.kind==="PAYOUT"?"Payout":"Reversal"}: {money(x.amount)}</p>)}</details>}</td></tr>})}</tbody></table></div>
      {capabilities.complete&&["APPROVED","PAYOUT_IN_PROGRESS"].includes(shareout.status)&&<button disabled={busy||difference!==0||items.some(x=>x.net_paid!==x.final_entitlement)} onClick={()=>post(`/api/v1/groups/${groupId}/cycles/${cycleId}/shareout/${shareout.id}/complete`)}>Complete share-out</button>}{shareout.status==="COMPLETED"&&<p><strong>SHARE-OUT COMPLETED</strong></p>}
    </section>}
    {shareout?.status==="COMPLETED"&&<section className="panel" style={{padding:20}}><h2>Social Fund carry-forward</h2><p>Source cycle balance: {money(closure.proof.social_cash)}</p>{closure.proof.social_cash==="0.00"?<p>No Social Fund balance requires carry-forward.</p>:next?.status==="READY"&&capabilities.operate?<button disabled={busy} onClick={()=>post(`/api/v1/groups/${groupId}/cycles/${cycleId}/social-fund/carry-forward`,{targetCycleId:next.id,idempotencyKey:crypto.randomUUID()})}>Carry forward to Cycle {next.cycle_number}</button>:<p>Create a READY next cycle before carrying the Social Fund forward.</p>}</section>}
    {finalReconciliation?.eligible&&capabilities.refreshReconciliation&&<FinalReconciliationRefresh groupId={groupId} cycleId={cycleId} state={finalReconciliation}/>} 
    <section className="panel" style={{padding:20}}><h2>Cycle closure readiness</h2>{closure.blockingIssues.map(code=><p key={code}>☐ {explain(code)}</p>)}{closure.ready&&<p>✓ Share-out, reconciliation, Social Fund, loan and closing-account checks are ready.</p>}{capabilities.close&&closure.ready&&<button disabled={busy} onClick={()=>post(`/api/v1/groups/${groupId}/cycles/${cycleId}/close`)}>Close cycle</button>}{closure.proof.cycle_status==="CLOSED"&&next?.status==="READY"&&capabilities.cycleManage&&<button disabled={busy} onClick={()=>post(`/api/v1/groups/${groupId}/cycles/${next.id}/activate`)}>Activate Cycle {next.cycle_number}</button>}{!next&&<p><Link href={`/groups/${groupId}/cycle?createNext=1`}>Create the next cycle using the existing cycle workflow.</Link></p>}</section>
    <section className="panel" style={{padding:20}}><h2>Recommended close-out sequence</h2><p>Complete final-meeting transactions, complete Share-out payouts, carry the Social Fund forward, refresh the final reconciliation if balances changed, then close the cycle.</p></section>
  </div>;
}
