"use client";
import Image from "next/image";
import Link from "next/link";
import { usePathname } from "next/navigation";

const adminSections=[["Programme",[["Dashboard","/dashboard","grid"],["Projects","/projects","folder"],["Groups","/groups","groups"],["Agents","/facilitators","agents"]]],["Administration",[["Users","/users","users"],["Membership Requests","/membership-requests","requests"],["Notifications","/notifications","bell"],["Settings","/settings","settings"]]]];
const agentSections=[["Workspace",[["Dashboard","/dashboard","grid"],["My Groups","/groups","groups"],["Create Savings Group","/groups/new","plus"],["Membership Requests","/membership-requests","requests"]]],["Account",[["Notifications","/notifications","bell"],["Profile","/settings","settings"]]]];
const memberSections=[["My savings groups",[["Dashboard","/dashboard","grid"],["My Groups","/my-groups","groups"]]]];
function Icon({name}){const paths={grid:<><rect x="3" y="3" width="7" height="7"/><rect x="14" y="3" width="7" height="7"/><rect x="3" y="14" width="7" height="7"/><rect x="14" y="14" width="7" height="7"/></>,folder:<path d="M3 7h7l2-3h9v16H3z"/>,groups:<><circle cx="9" cy="8" r="3"/><circle cx="17" cy="9" r="2.5"/><path d="M3 20c0-4 2.5-6 6-6s6 2 6 6M15 15c3.5 0 6 1.6 6 5"/></>,agents:<><circle cx="12" cy="8" r="4"/><path d="M4 21c0-5 3.2-8 8-8s8 3 8 8"/></>,users:<><circle cx="8" cy="8" r="3"/><circle cx="17" cy="8" r="3"/><path d="M2 21c0-4 2.5-7 6-7s6 3 6 7M13 15c1-.7 2.2-1 4-1 3 0 5 2.5 5 7"/></>,requests:<><path d="M6 3h12v18H6z"/><path d="M9 8h6M9 12h6M9 16h4"/></>,bell:<><path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9"/><path d="M10 21h4"/></>,settings:<><circle cx="12" cy="12" r="3"/><path d="M12 2v3M12 19v3M2 12h3M19 12h3M5 5l2 2M17 17l2 2M19 5l-2 2M7 17l-2 2"/></>,plus:<path d="M12 5v14M5 12h14"/>};return <svg className="nav-icon" viewBox="0 0 24 24" aria-hidden="true">{paths[name]}</svg>}
export default function Sidebar({user,open=false,onNavigate}){const pathname=usePathname(),elevated=user.roles?.some(role=>["SUPER_ADMIN","PROJECT_ADMIN","STATE_COORDINATOR"].includes(role)),memberOnly=user.roles?.includes("VSLA_MEMBER")&&!user.roles.some(role=>["SUPER_ADMIN","PROJECT_ADMIN","STATE_COORDINATOR","FACILITATOR"].includes(role)),sections=memberOnly?memberSections:user.roles?.includes("FACILITATOR")&&!elevated?agentSections:adminSections;return <aside className={`app-sidebar ${open?"is-open":""}`} aria-label="Application navigation"><Link className="app-brand" href={memberOnly?"/my-groups":"/dashboard"} onClick={onNavigate}><Image className="app-brand-logo" src="/cccrn-logo.png" alt="CCCRN logo" width={190} height={148}/><span><strong>Visave</strong></span></Link><div className="programme-mark">Visave....Community Finance Made Clearer!!!</div><nav className="app-navigation">{sections.map(([label,items])=><section key={label}><p>{label}</p>{items.map(([name,href,icon])=>{const active=href==="/dashboard"?pathname===href:pathname===href||pathname.startsWith(`${href}/`);return <Link key={name} href={href} className={active?"active":""} aria-current={active?"page":undefined} onClick={onNavigate}><Icon name={icon}/><span>{name}</span></Link>})}</section>)}</nav></aside>}
